### ISSUE TITLE
[v1.0.1] Seems that absolute path is hardcoded in source code

### ISSUE THREAD

**Issue by balazs-zsoldos** [revolist/angular-datagrid#1]
Error when using the lib and compiling.

    node_modules/@revolist/revogrid/dist/types/components.d.ts:87:77 - error TS2307: Cannot find module '/home/runner/work/revogrid/revogrid/src/interfaces'.

**Comment by revolist** [comment]
Should be fine now, the compiler was using incorrect references for type definitions.
