### ISSUE TITLE
Got issue when npm install in angular 17

### ISSUE THREAD

**Issue by TONG77777** [revolist/angular-datagrid#12]
waiting for update version of angular-datagrid...
<img width="769" alt="Screenshot 2023-12-06 at 12 03 24 PM" src="https://github.com/revolist/angular-datagrid/assets/78796067/aefc6918-80b4-4781-8e74-886f2f3ffff9">

**Comment by NomahS** [comment]
Hello, did you find any solution ? I got the same error with Angular 17.

**Comment by MOmenx0** [comment]
> Hello, did you find any solution ? I got the same error with Angular 17.

any solution ?

**Comment by revolist** [comment]
Updated to 4+
New renders, standalone components and full angular support
