### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by rogsmith** [revolist/angular-datagrid#2]
Error: node_modules/@revolist/angular-datagrid/dist/revogrid.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

**Comment by revolist** [comment]
@rogsmith it's not very clear how to reproduce it.
Please provide some steps to follow. We'll configure it.

**Comment by rogsmith** [comment]
So I just ran npm install in my Angular app, and then tried to start my app.

**Comment by revolist** [comment]
@rogsmith, I'll provide you with working angular example by the end of the day.
We are updating our angular library at this moment for easier integration.

**Comment by rogsmith** [comment]
@revolist perfect thank you.

**Comment by revolist** [comment]
@rogsmith 
Documentation has been updated:
https://revolist.github.io/revogrid/guide/framework.angular.overview.html

The sample has been updated:
https://codesandbox.io/s/angular-datagrid-overview-d5i0b?fontsize=14&hidenavigation=1&theme=dark&file=/src/app/app.module.ts

Github initial Repo provided:
https://github.com/revolist/angular-datagrid-test
