### ISSUE TITLE
Found typo in revogr-header.d.ts

### ISSUE THREAD

**Issue by MaximeKoitsalu** [revolist/angular-datagrid#3]
Hey,

I'm using revolist/angular-datagrid@3.0.1
In the RevogrHeaderComponent class declaration `revogr-header.d.ts`, it seems that there is a type on line 18. 

It should say "headerDblClick" instead of "headerdblClick"

![image](https://user-images.githubusercontent.com/8655862/114013813-41080f00-9868-11eb-82f1-04a926f4b451.png)

**Comment by revolist** [comment]
@MaximeKoitsalu issue was present 'coz incompatible versions of core
Fixed.
