### ISSUE TITLE
typo for headerResize

### ISSUE THREAD

**Issue by justin-aiassets** [revolist/angular-datagrid#5]
I got the following error when running my angular app.  Can you please have a look at it and fix the typo for headerResize?

Error: node_modules/@revolist/angular-datagrid/dist/proxies/revogrid.d.ts:164:42 - error TS2339: Property 'headerResize' does not exist on type 'RevogrHeaderComponent'.

164     headerResize: IRevogrHeaderComponent['headerResize'];
                                             ~~~~~~~~~~~~~~

The version I am using is 3.0.52.
Thanks.

**Comment by florentsuc** [comment]
I have the same issue.

**Comment by florentsuc** [comment]
To solve it, I replaced `angular-datagrid` by `revolist/revogrid` using the web component version: see https://revolist.github.io/revogrid/guide/framework.angular.webcomponent.html#including-the-custom-elements-schema

**Comment by revolist** [comment]
Updated to 4+
