### ISSUE TITLE
Impossible to the use the library

### ISSUE THREAD

**Issue by ArthurB73** [revolist/angular-datagrid#6]
I'm trying to use the library in my Angular project but I'm having a problem.

Error: node_modules/@revolist/angular-datagrid/dist/proxies/revogrid.d.ts:164:42 - error TS2339: Property 'headerResize' does not exist on type 'RevogrHeaderComponent'.

164 headerResize: IRevogrHeaderComponent['headerResize'];

following this problem, I tried to use the library in WebComponent. I have no more errors by angular CLI but I have nothing displayed in my component.

angular-datagrid version : 3.0.52
Angular version : 12.1.3

Thanks

**Comment by revolist** [comment]
Updated to 4+
New renders, standalone components and full angular support
