### ISSUE TITLE
Typo in HeaderResize property in angular 13.2.0

### ISSUE THREAD

**Issue by wondie** [revolist/angular-datagrid#8]
After installing and building, I get this error below. 
```

Error: node_modules/@revolist/angular-datagrid/dist/proxies/revogrid.d.ts:164:42 - error TS2339: Property 'headerResize' does not exist on type 'RevogrHeaderComponent'.

164     headerResize: IRevogrHeaderComponent['headerResize'];
                                             ~~~~~~~~~~~~~~

```
The error is gone once I edited it to `RevogrHeaderComponent['headerresize'];` in `node_modules/@revolist/angular-datagrid/dist/proxies/revogrid.d.ts` line 164.

**Comment by andrewames** [comment]
Can this be resolved? Easy enough to rename it but my build server is going to pull this again and have the issue in prod

**Comment by bahablgn** [comment]
the same issue, please fix this.

**Comment by revolist** [comment]
Updated to 4+
New renders, standalone components and full angular support
